import Virtual from '../images/virtual.svg';

const Sdata = [{
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
},
{
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
}, {
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
}, {
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
}, {
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
}, {
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
}, {
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
}, {
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
}, {
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
},
{
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
}, {
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
},{
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
},{
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
},{
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
},{
    head: "Lean Six Sigma Green Belt",
    virtuh1: "Virtual",
    virtup: "Best selling Six Sigma Virtual Courses",
    virtu_2img: Virtual,
    virtu_2p: "Virtual",
    date: "15",
    day: "Mon",
    month: "May",
    year: "2023",
    pricep: "£1995",
    priceh2: "£1495",
    enquirebutton: "Enquiry",
    durationh3: "Duration",
    durationp: "05 Days",
    view_more: "View More Dates",
    rightangle: "",
    contactenvelop: "",
    contactphone: "",
    book_nowbutton: "Book Now",
},

];

export default Sdata;